// 此文件由工具产生，请勿手动修改！

package problems

import "net/http"

var problemStatuses = map[int]struct{}{
	http.StatusBadRequest:                    {},
	http.StatusUnauthorized:                  {},
	http.StatusPaymentRequired:               {},
	http.StatusForbidden:                     {},
	http.StatusNotFound:                      {},
	http.StatusMethodNotAllowed:              {},
	http.StatusNotAcceptable:                 {},
	http.StatusProxyAuthRequired:             {},
	http.StatusRequestTimeout:                {},
	http.StatusConflict:                      {},
	http.StatusGone:                          {},
	http.StatusLengthRequired:                {},
	http.StatusPreconditionFailed:            {},
	http.StatusRequestEntityTooLarge:         {},
	http.StatusRequestURITooLong:             {},
	http.StatusUnsupportedMediaType:          {},
	http.StatusRequestedRangeNotSatisfiable:  {},
	http.StatusExpectationFailed:             {},
	http.StatusTeapot:                        {},
	http.StatusMisdirectedRequest:            {},
	http.StatusUnprocessableEntity:           {},
	http.StatusLocked:                        {},
	http.StatusFailedDependency:              {},
	http.StatusTooEarly:                      {},
	http.StatusUpgradeRequired:               {},
	http.StatusPreconditionRequired:          {},
	http.StatusTooManyRequests:               {},
	http.StatusRequestHeaderFieldsTooLarge:   {},
	http.StatusUnavailableForLegalReasons:    {},
	http.StatusInternalServerError:           {},
	http.StatusNotImplemented:                {},
	http.StatusBadGateway:                    {},
	http.StatusServiceUnavailable:            {},
	http.StatusGatewayTimeout:                {},
	http.StatusHTTPVersionNotSupported:       {},
	http.StatusVariantAlsoNegotiates:         {},
	http.StatusInsufficientStorage:           {},
	http.StatusLoopDetected:                  {},
	http.StatusNotExtended:                   {},
	http.StatusNetworkAuthenticationRequired: {},
}
