language: go

env:
  - GO111MODULE=on

branchs:
  only:
  - master
  - /^v*$/

os:
  - linux
  - osx
  - windows

go:
  - tip
  - 1.15.x
  - 1.14.x

script: 
  - go generate -v ./...
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
