language: go

os:
  - linux
  - osx
  - windows

env:
  - GO111MODULE=on

go:
  - tip
  - 1.12
  - 1.11.x

stages:
  - test

  - name: build-posix
    if: os != windows

  - name: build-windows
    if: os = windows

jobs:
  include:
    - stage: test
      script:
        - go generate -v ./...
        - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

    - stage: build-posix
      script: ./build/web.sh

    - stage: build-windows
      script: ./build/web.bat

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
