language: go

env:
  - GO111MODULE=on

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      os:
        - linux
        - osx
        - windows
      go:
        - tip
        - 1.12
        - 1.11.x
      script:
        - go generate -v ./...
        - go test -v -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    # 简单尝试编译是否成功
    - stage: build
      os:
        - linux
        - osx
        - windows
      go:
        - tip
        - 1.12
        - 1.11.x
      script: go build ./cmd/web

matrix:
  allow_failures:
    - go: tip
