language: go

os:
  - linux
  - osx

go:
  - tip
  - "1.10"

install:
  - go get github.com/issue9/assert
  - go get github.com/issue9/context
  - go get github.com/issue9/middleware
  - go get github.com/issue9/logs
  - go get github.com/issue9/mux
  - go get github.com/issue9/utils
  - go get github.com/issue9/is
  - go get github.com/issue9/version

  - go get gopkg.in/yaml.v2
  - go get golang.org/x/text

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic $(go list ./...| grep -v /vendor/)

after_success:
  - bash <(curl -s https://codecov.io/bash)
