language: go

os:
  - linux
  - osx
  - windows

env:
  - GO111MODULE=on

go:
  - tip
  - 1.12
  - 1.11.x

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      script:
        - go generate -v ./...
        - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

    # 简单尝试编译是否成功
    - stage: build
      script: go build ./cmd/web

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
