language: go

env:
  - GO111MODULE=on

branchs:
  only:
  - master
  - /^v*$/

os:
  - linux
  - osx
  - windows

go:
  - tip
  - 1.12.x
  - 1.11.x

stages:
  - test
  - build

jobs:
  include:
    - script: go generate -v ./...
    - script: go test -v -coverprofile=coverage.txt -covermode=atomic ./...
    - after_success: bash <(curl -s https://codecov.io/bash)

    # 简单尝试编译是否成功
    - stage: build
      os: linux
      go: 1.12.x
      script: go build ./cmd/web

    - stage: build
      os: windows
      go: 1.12.x
      script: go build ./cmd/web

    - stage: build
      os: macOS
      go: 1.12.x
      script: go build ./cmd/web

matrix:
  allow_failures:
    - go: tip
