language: go

os:
  - linux
  - osx

go:
  - tip
  - 1.11
  - "1.10"

install:
  - go get github.com/issue9/assert
  - go get github.com/issue9/middleware
  - go get github.com/issue9/logs
  - go get github.com/issue9/mux
  - go get github.com/issue9/utils
  - go get github.com/issue9/is
  - go get github.com/issue9/version
  - go get github.com/issue9/query
  - go get github.com/issue9/term/colors

  - go get gopkg.in/yaml.v2
  - go get golang.org/x/text

script:
  - ./test.sh -cv

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
