version: 2
project_name: web

release:
  github:
    owner: issue9
    name: web
  name_template: "{{.Tag}}"

builds:
  - id: web

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64
      - arm64

    ignore:
      - goos: windows
        goarch: arm64

    main: ./

    binary: web

    flags:
      - -trimpath

    ldflags:
      - -s -w -X main.commits={{.Commit}} -X main.version={{.Version}}

brews:
  - repository:
      owner: caixw
      name: homebrew-brew
    url_template: "https://github.com/issue9/web/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    directory: Formula
    homepage: "https://github.com/issue9/web"
    description: 框架 web 的辅助工具
    license: MIT

archives:
  - builds:
      - web
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  groups:
    - title: 新功能
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "BUG 修复"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
