name: Cache
on: [push, pull_request]

jobs:

  cache:
    name: Cache
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ['1.18.x', '1.19.x']

    services:
      memcached:
        image: memcached:latest
        ports:
          - 11211:11211
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Test
        env:
          LANG: en
        run: go test -v -coverprofile='coverage.txt' -covermode=atomic ./internal/caches/...

      - name: Upload Coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
