name: Cmd
on: [push, pull_request]

jobs:

  test:
    name: cmd
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        go: ['1.21.x']

    steps:

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Vet
        run: |
          cd cmd/web
          go vet -v ./...
        
      - name: Test
        env:
          LANG: en
        run: |
          cd cmd/web
          go test -v ./...
