name: Test
on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        go: ['1.18.x', '1.19.x']

    steps:

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Vet
        run: go vet -v ./...
        
      - name: Test
        env:
          LANG: en
        run: go test $(go list ./... | grep -v internal/caches) -v -coverprofile='coverage.txt' -covermode=atomic

      - name: Upload Coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
